<?php

namespace Database\Seeders;

use App\Models\InventoryMovement;
use App\Models\SparePart;
use App\Models\User;
use Illuminate\Database\Seeder;

class SparePartSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::where('role', 'admin')->first()->id;

        $parts = [
            // ── Aceites ───────────────────────────────────────────────
            [
                'name'           => 'Aceite Motor 5W-30 Sintético (1L)',
                'sku'            => 'ACE-5W30-1L',
                'description'    => 'Aceite de motor sintético 5W-30. Ideal para motores modernos a gasolina.',
                'category'       => 'aceite',
                'unit'           => 'litro',
                'unit_price'     => 95.00,
                'purchase_price' => 65.00,
                'stock'          => 80,
                'minimum_stock'  => 20,
                'location'       => 'Estante A-1',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],
            [
                'name'           => 'Aceite Motor 10W-40 Semisintético (1L)',
                'sku'            => 'ACE-10W40-1L',
                'description'    => 'Aceite semisintético 10W-40. Compatible con motores gasolina y diesel ligero.',
                'category'       => 'aceite',
                'unit'           => 'litro',
                'unit_price'     => 72.00,
                'purchase_price' => 48.00,
                'stock'          => 60,
                'minimum_stock'  => 15,
                'location'       => 'Estante A-1',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],
            [
                'name'           => 'Aceite Motor 15W-40 Mineral (1L)',
                'sku'            => 'ACE-15W40-1L',
                'description'    => 'Aceite mineral 15W-40. Para motores diesel y gasolina de trabajo pesado.',
                'category'       => 'aceite',
                'unit'           => 'litro',
                'unit_price'     => 55.00,
                'purchase_price' => 35.00,
                'stock'          => 45,
                'minimum_stock'  => 10,
                'location'       => 'Estante A-2',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],
            [
                'name'           => 'Aceite Transmisión ATF Dextron VI (1L)',
                'sku'            => 'ACE-ATF-1L',
                'description'    => 'Aceite ATF Dextron VI para transmisiones automáticas modernas.',
                'category'       => 'aceite',
                'unit'           => 'litro',
                'unit_price'     => 110.00,
                'purchase_price' => 78.00,
                'stock'          => 30,
                'minimum_stock'  => 8,
                'location'       => 'Estante A-2',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],
            [
                'name'           => 'Aceite Dirección Hidráulica (500ml)',
                'sku'            => 'ACE-DH-500',
                'description'    => 'Aceite para dirección hidráulica. Compatible con la mayoría de vehículos.',
                'category'       => 'aceite',
                'unit'           => 'pieza',
                'unit_price'     => 85.00,
                'purchase_price' => 55.00,
                'stock'          => 3,  // stock bajo — para demostración de alerta
                'minimum_stock'  => 8,
                'location'       => 'Estante A-3',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],

            // ── Filtros ───────────────────────────────────────────────
            [
                'name'           => 'Filtro de Aceite Universal Toyota/Nissan',
                'sku'            => 'FIL-ACE-TN',
                'description'    => 'Filtro de aceite compatible con Toyota Corolla, Nissan Sentra/March y modelos similares.',
                'category'       => 'filtro',
                'unit'           => 'pieza',
                'unit_price'     => 120.00,
                'purchase_price' => 75.00,
                'stock'          => 35,
                'minimum_stock'  => 10,
                'location'       => 'Estante B-1',
                'supplier'       => 'Filtros México SA',
                'is_active'      => true,
            ],
            [
                'name'           => 'Filtro de Aire Panel (Genérico)',
                'sku'            => 'FIL-AIRE-GEN',
                'description'    => 'Filtro de aire tipo panel de alta filtración. Consultar medidas según modelo.',
                'category'       => 'filtro',
                'unit'           => 'pieza',
                'unit_price'     => 180.00,
                'purchase_price' => 110.00,
                'stock'          => 25,
                'minimum_stock'  => 8,
                'location'       => 'Estante B-1',
                'supplier'       => 'Filtros México SA',
                'is_active'      => true,
            ],
            [
                'name'           => 'Filtro de Combustible Universal',
                'sku'            => 'FIL-COMB-UNI',
                'description'    => 'Filtro de combustible en línea. Compatible con vehículos a gasolina.',
                'category'       => 'filtro',
                'unit'           => 'pieza',
                'unit_price'     => 95.00,
                'purchase_price' => 60.00,
                'stock'          => 20,
                'minimum_stock'  => 6,
                'location'       => 'Estante B-2',
                'supplier'       => 'Filtros México SA',
                'is_active'      => true,
            ],
            [
                'name'           => 'Filtro de Habitáculo (Cabina)',
                'sku'            => 'FIL-HAB-GEN',
                'description'    => 'Filtro de cabina para aire acondicionado. Retiene polvo, polen y partículas.',
                'category'       => 'filtro',
                'unit'           => 'pieza',
                'unit_price'     => 140.00,
                'purchase_price' => 85.00,
                'stock'          => 4,  // stock bajo
                'minimum_stock'  => 8,
                'location'       => 'Estante B-2',
                'supplier'       => 'Filtros México SA',
                'is_active'      => true,
            ],

            // ── Bujías ────────────────────────────────────────────────
            [
                'name'           => 'Bujías Iridio NGK (juego 4 piezas)',
                'sku'            => 'BUJ-NGK-IR4',
                'description'    => 'Bujías de iridio NGK. Mayor duración y rendimiento. Para motores de 4 cilindros.',
                'category'       => 'bujia',
                'unit'           => 'juego',
                'unit_price'     => 580.00,
                'purchase_price' => 380.00,
                'stock'          => 15,
                'minimum_stock'  => 4,
                'location'       => 'Estante C-1',
                'supplier'       => 'NGK de México',
                'is_active'      => true,
            ],
            [
                'name'           => 'Bujías Platino Bosch (juego 4 piezas)',
                'sku'            => 'BUJ-BSH-PT4',
                'description'    => 'Bujías de platino Bosch. Buena relación costo/duración para motores estándar.',
                'category'       => 'bujia',
                'unit'           => 'juego',
                'unit_price'     => 320.00,
                'purchase_price' => 200.00,
                'stock'          => 18,
                'minimum_stock'  => 5,
                'location'       => 'Estante C-1',
                'supplier'       => 'Bosch Automotriz',
                'is_active'      => true,
            ],
            [
                'name'           => 'Bujías Cobre Estándar (juego 4 piezas)',
                'sku'            => 'BUJ-CU-4',
                'description'    => 'Bujías de cobre estándar. Económicas, para vehículos sin altas exigencias.',
                'category'       => 'bujia',
                'unit'           => 'juego',
                'unit_price'     => 180.00,
                'purchase_price' => 110.00,
                'stock'          => 22,
                'minimum_stock'  => 6,
                'location'       => 'Estante C-2',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],

            // ── Frenos ────────────────────────────────────────────────
            [
                'name'           => 'Pastillas de Freno Delanteras Brembo',
                'sku'            => 'FRE-PAS-DEL-BRE',
                'description'    => 'Pastillas de freno delanteras Brembo. Alta resistencia al calor. Juego de 4 pastillas.',
                'category'       => 'freno',
                'unit'           => 'juego',
                'unit_price'     => 420.00,
                'purchase_price' => 270.00,
                'stock'          => 12,
                'minimum_stock'  => 4,
                'location'       => 'Estante D-1',
                'supplier'       => 'Brembo Distribuciones',
                'is_active'      => true,
            ],
            [
                'name'           => 'Pastillas de Freno Traseras (Genérico)',
                'sku'            => 'FRE-PAS-TRA-GEN',
                'description'    => 'Pastillas de freno traseras genéricas. Buen rendimiento a precio accesible.',
                'category'       => 'freno',
                'unit'           => 'juego',
                'unit_price'     => 280.00,
                'purchase_price' => 170.00,
                'stock'          => 10,
                'minimum_stock'  => 4,
                'location'       => 'Estante D-1',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],
            [
                'name'           => 'Disco de Freno Delantero (par)',
                'sku'            => 'FRE-DISC-DEL',
                'description'    => 'Discos de freno delanteros ventilados. Par (2 piezas). Dimensiones estándar 280mm.',
                'category'       => 'freno',
                'unit'           => 'par',
                'unit_price'     => 750.00,
                'purchase_price' => 480.00,
                'stock'          => 2,  // stock crítico — para demo
                'minimum_stock'  => 4,
                'location'       => 'Estante D-2',
                'supplier'       => 'Brembo Distribuciones',
                'is_active'      => true,
            ],
            [
                'name'           => 'Líquido de Frenos DOT 4 (500ml)',
                'sku'            => 'FRE-LIQ-DOT4',
                'description'    => 'Líquido de frenos DOT 4. Punto de ebullición 260°C. Botella 500ml.',
                'category'       => 'freno',
                'unit'           => 'pieza',
                'unit_price'     => 95.00,
                'purchase_price' => 55.00,
                'stock'          => 18,
                'minimum_stock'  => 6,
                'location'       => 'Estante D-3',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],

            // ── Refrigerantes ─────────────────────────────────────────
            [
                'name'           => 'Refrigerante Anticongelante Verde (1L)',
                'sku'            => 'REF-VRD-1L',
                'description'    => 'Anticongelante/refrigerante convencional verde. Listo para usar diluido al 50%.',
                'category'       => 'refrigerante',
                'unit'           => 'litro',
                'unit_price'     => 65.00,
                'purchase_price' => 40.00,
                'stock'          => 40,
                'minimum_stock'  => 12,
                'location'       => 'Estante E-1',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],
            [
                'name'           => 'Refrigerante OAT Rojo (1L)',
                'sku'            => 'REF-OAT-1L',
                'description'    => 'Refrigerante OAT rojo de larga duración. Para vehículos europeos y asiáticos modernos.',
                'category'       => 'refrigerante',
                'unit'           => 'litro',
                'unit_price'     => 90.00,
                'purchase_price' => 58.00,
                'stock'          => 5,  // stock bajo
                'minimum_stock'  => 10,
                'location'       => 'Estante E-1',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],

            // ── Correas ───────────────────────────────────────────────
            [
                'name'           => 'Correa Serpentín Multirriba (Universal)',
                'sku'            => 'COR-SERP-UNI',
                'description'    => 'Correa serpentín multirriba. Consultar medidas según modelo de vehículo.',
                'category'       => 'correa',
                'unit'           => 'pieza',
                'unit_price'     => 280.00,
                'purchase_price' => 175.00,
                'stock'          => 12,
                'minimum_stock'  => 4,
                'location'       => 'Estante F-1',
                'supplier'       => 'Gates México',
                'is_active'      => true,
            ],
            [
                'name'           => 'Kit Correa de Distribución Toyota',
                'sku'            => 'COR-DIST-TOY',
                'description'    => 'Kit completo de distribución para Toyota: correa, tensor, polea y bomba de agua.',
                'category'       => 'correa',
                'unit'           => 'kit',
                'unit_price'     => 950.00,
                'purchase_price' => 620.00,
                'stock'          => 6,
                'minimum_stock'  => 2,
                'location'       => 'Estante F-1',
                'supplier'       => 'Gates México',
                'is_active'      => true,
            ],

            // ── Baterías ──────────────────────────────────────────────
            [
                'name'           => 'Batería Bosch 65Ah 12V',
                'sku'            => 'BAT-BSH-65',
                'description'    => 'Batería de arranque Bosch 65Ah 12V. Garantía 18 meses. Compatible con la mayoría de vehículos compactos.',
                'category'       => 'bateria',
                'unit'           => 'pieza',
                'unit_price'     => 1850.00,
                'purchase_price' => 1300.00,
                'stock'          => 8,
                'minimum_stock'  => 3,
                'location'       => 'Estante G-1',
                'supplier'       => 'Bosch Automotriz',
                'is_active'      => true,
            ],
            [
                'name'           => 'Batería Optima 75Ah AGM',
                'sku'            => 'BAT-OPT-75',
                'description'    => 'Batería AGM de ciclo profundo. Para vehículos con sistema Start-Stop y electrónicos avanzados.',
                'category'       => 'bateria',
                'unit'           => 'pieza',
                'unit_price'     => 3200.00,
                'purchase_price' => 2200.00,
                'stock'          => 3,
                'minimum_stock'  => 2,
                'location'       => 'Estante G-1',
                'supplier'       => 'Distribuidora Automotriz del Norte',
                'is_active'      => true,
            ],

            // ── Otros ─────────────────────────────────────────────────
            [
                'name'           => 'Silicona RTV Gris (90ml)',
                'sku'            => 'OTR-RTV-GRI',
                'description'    => 'Silicona RTV gris resistente a altas temperaturas. Para sellar juntas de motor.',
                'category'       => 'otro',
                'unit'           => 'pieza',
                'unit_price'     => 85.00,
                'purchase_price' => 50.00,
                'stock'          => 20,
                'minimum_stock'  => 5,
                'location'       => 'Estante H-1',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],
            [
                'name'           => 'Grasa de Lítio (500g)',
                'sku'            => 'OTR-GRS-LIT',
                'description'    => 'Grasa de litio multipropósito para rodamientos, rótulas y componentes de suspensión.',
                'category'       => 'otro',
                'unit'           => 'pieza',
                'unit_price'     => 75.00,
                'purchase_price' => 45.00,
                'stock'          => 15,
                'minimum_stock'  => 4,
                'location'       => 'Estante H-1',
                'supplier'       => 'Refacciones Express',
                'is_active'      => true,
            ],
        ];

        foreach ($parts as $partData) {
            $part = SparePart::create($partData);

            // Registrar movimiento de inventario inicial
            InventoryMovement::create([
                'spare_part_id' => $part->id,
                'user_id'       => $adminId,
                'type'          => 'in',
                'quantity'      => $part->stock,
                'reason'        => 'Inventario inicial — carga de sistema',
                'reference'     => 'SEED-' . date('Ym'),
            ]);
        }
    }
}
